theme = "stip"

[Author]
    name = "Dr Dayyanah Sumodhee"
    bio = "Health Psychologist"

[params]
    [[params.links]]
        icon = "github"
        title = "Github"
        url = "https://github.com/Dsumodhee"
