[context.production.environment]
  HUGO_VERSION = "0.55.6"
  HUGO_ENV = "production"

[build]
  publish = "public"
  command = "git clone https://github.com/Dsumodhee/stip-hugo.git themes/stip && hugo server -t stip && hugo --minify"
